package com.example.coursework_bd_24.utility.sqlutility;

import com.example.coursework_bd_24.model.WeightData;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class WeightDataSQLFieldsUtil implements SQLFieldsNameUtil<WeightData>, SQLFieldsDataUtil<WeightData> {

    @Override
    public List<String> getStringNamesOfFields() {
        return List.of( "number_col_1", "number_col_2", "number_col_3", "number_col_4", "number_col_5", "number_col_6", "number_col_7", "number_col_8", "number_col_9", "number_col_10", "number_col_11", "number_col_12", "number_col_13", "number_col_14", "number_col_15", "number_col_16", "number_col_17", "number_col_18", "number_col_19", "number_col_20", "number_col_21", "number_col_22", "number_col_23", "number_col_24", "number_col_25", "number_col_26", "number_col_27", "number_col_28", "number_col_29", "number_col_30", "number_col_31", "number_col_32", "number_col_33", "number_col_34", "number_col_35", "number_col_36", "number_col_37", "number_col_38", "number_col_39", "number_col_40", "number_col_41", "number_col_42", "number_col_43", "number_col_44", "number_col_45", "number_col_46", "number_col_47", "number_col_48", "number_col_49", "number_col_50", "number_col_51", "number_col_52", "number_col_53", "number_col_54", "number_col_55", "number_col_56", "number_col_57", "number_col_58", "number_col_59", "number_col_60", "number_col_61", "number_col_62", "number_col_63", "number_col_64", "number_col_65", "number_col_66", "number_col_67", "number_col_68", "number_col_69", "number_col_70", "number_col_71", "number_col_72", "number_col_73", "number_col_74", "number_col_75", "number_col_76", "number_col_77", "number_col_78", "number_col_79", "number_col_80", "number_col_81", "number_col_82", "number_col_83", "number_col_84", "number_col_85", "number_col_86", "number_col_87", "number_col_88", "number_col_89", "number_col_90", "number_col_91", "number_col_92", "number_col_93", "number_col_94", "number_col_95", "number_col_96", "number_col_97", "number_col_98", "number_col_99", "number_col_100", "string_col_1", "string_col_2", "string_col_3", "string_col_4", "string_col_5", "string_col_6", "string_col_7", "string_col_8", "string_col_9", "string_col_10", "string_col_11", "string_col_12", "string_col_13", "string_col_14", "string_col_15", "string_col_16", "string_col_17", "string_col_18", "string_col_19", "string_col_20", "string_col_21", "string_col_22", "string_col_23", "string_col_24", "string_col_25", "string_col_26", "string_col_27", "string_col_28", "string_col_29", "string_col_30", "string_col_31", "string_col_32", "string_col_33", "string_col_34", "string_col_35", "string_col_36", "string_col_37", "string_col_38", "string_col_39", "string_col_40", "string_col_41", "string_col_42", "string_col_43", "string_col_44", "string_col_45", "string_col_46", "string_col_47", "string_col_48", "string_col_49", "string_col_50", "string_col_51", "string_col_52", "string_col_53", "string_col_54", "string_col_55", "string_col_56", "string_col_57", "string_col_58", "string_col_59", "string_col_60", "string_col_61", "string_col_62", "string_col_63", "string_col_64", "string_col_65", "string_col_66", "string_col_67", "string_col_68", "string_col_69", "string_col_70", "string_col_71", "string_col_72", "string_col_73", "string_col_74", "string_col_75", "string_col_76", "string_col_77", "string_col_78", "string_col_79", "string_col_80", "string_col_81", "string_col_82", "string_col_83", "string_col_84", "string_col_85", "string_col_86", "string_col_87", "string_col_88", "string_col_89", "string_col_90", "string_col_91", "string_col_92", "string_col_93", "string_col_94", "string_col_95", "string_col_96", "string_col_97", "string_col_98", "string_col_99", "string_col_100");
    }

    @Override
    public List<String> getStringDataOfFields(WeightData weightData) {
        List<String> fields = new ArrayList<>();
        fields.add(weightData.getLongCol1() != null ? weightData.getLongCol1().toString() : "NULL");
        fields.add(weightData.getLongCol2() != null ? weightData.getLongCol2().toString() : "NULL");
        fields.add(weightData.getLongCol3() != null ? weightData.getLongCol3().toString() : "NULL");
        fields.add(weightData.getLongCol4() != null ? weightData.getLongCol4().toString() : "NULL");
        fields.add(weightData.getLongCol5() != null ? weightData.getLongCol5().toString() : "NULL");
        fields.add(weightData.getLongCol6() != null ? weightData.getLongCol6().toString() : "NULL");
        fields.add(weightData.getLongCol7() != null ? weightData.getLongCol7().toString() : "NULL");
        fields.add(weightData.getLongCol8() != null ? weightData.getLongCol8().toString() : "NULL");
        fields.add(weightData.getLongCol9() != null ? weightData.getLongCol9().toString() : "NULL");
        fields.add(weightData.getLongCol10() != null ? weightData.getLongCol10().toString() : "NULL");
        fields.add(weightData.getLongCol11() != null ? weightData.getLongCol11().toString() : "NULL");
        fields.add(weightData.getLongCol12() != null ? weightData.getLongCol12().toString() : "NULL");
        fields.add(weightData.getLongCol13() != null ? weightData.getLongCol13().toString() : "NULL");
        fields.add(weightData.getLongCol14() != null ? weightData.getLongCol14().toString() : "NULL");
        fields.add(weightData.getLongCol15() != null ? weightData.getLongCol15().toString() : "NULL");
        fields.add(weightData.getLongCol16() != null ? weightData.getLongCol16().toString() : "NULL");
        fields.add(weightData.getLongCol17() != null ? weightData.getLongCol17().toString() : "NULL");
        fields.add(weightData.getLongCol18() != null ? weightData.getLongCol18().toString() : "NULL");
        fields.add(weightData.getLongCol19() != null ? weightData.getLongCol19().toString() : "NULL");
        fields.add(weightData.getLongCol20() != null ? weightData.getLongCol20().toString() : "NULL");
        fields.add(weightData.getLongCol21() != null ? weightData.getLongCol21().toString() : "NULL");
        fields.add(weightData.getLongCol22() != null ? weightData.getLongCol22().toString() : "NULL");
        fields.add(weightData.getLongCol23() != null ? weightData.getLongCol23().toString() : "NULL");
        fields.add(weightData.getLongCol24() != null ? weightData.getLongCol24().toString() : "NULL");
        fields.add(weightData.getLongCol25() != null ? weightData.getLongCol25().toString() : "NULL");
        fields.add(weightData.getLongCol26() != null ? weightData.getLongCol26().toString() : "NULL");
        fields.add(weightData.getLongCol27() != null ? weightData.getLongCol27().toString() : "NULL");
        fields.add(weightData.getLongCol28() != null ? weightData.getLongCol28().toString() : "NULL");
        fields.add(weightData.getLongCol29() != null ? weightData.getLongCol29().toString() : "NULL");
        fields.add(weightData.getLongCol30() != null ? weightData.getLongCol30().toString() : "NULL");
        fields.add(weightData.getLongCol31() != null ? weightData.getLongCol31().toString() : "NULL");
        fields.add(weightData.getLongCol32() != null ? weightData.getLongCol32().toString() : "NULL");
        fields.add(weightData.getLongCol33() != null ? weightData.getLongCol33().toString() : "NULL");
        fields.add(weightData.getLongCol34() != null ? weightData.getLongCol34().toString() : "NULL");
        fields.add(weightData.getLongCol35() != null ? weightData.getLongCol35().toString() : "NULL");
        fields.add(weightData.getLongCol36() != null ? weightData.getLongCol36().toString() : "NULL");
        fields.add(weightData.getLongCol37() != null ? weightData.getLongCol37().toString() : "NULL");
        fields.add(weightData.getLongCol38() != null ? weightData.getLongCol38().toString() : "NULL");
        fields.add(weightData.getLongCol39() != null ? weightData.getLongCol39().toString() : "NULL");
        fields.add(weightData.getLongCol40() != null ? weightData.getLongCol40().toString() : "NULL");
        fields.add(weightData.getLongCol41() != null ? weightData.getLongCol41().toString() : "NULL");
        fields.add(weightData.getLongCol42() != null ? weightData.getLongCol42().toString() : "NULL");
        fields.add(weightData.getLongCol43() != null ? weightData.getLongCol43().toString() : "NULL");
        fields.add(weightData.getLongCol44() != null ? weightData.getLongCol44().toString() : "NULL");
        fields.add(weightData.getLongCol45() != null ? weightData.getLongCol45().toString() : "NULL");
        fields.add(weightData.getLongCol46() != null ? weightData.getLongCol46().toString() : "NULL");
        fields.add(weightData.getLongCol47() != null ? weightData.getLongCol47().toString() : "NULL");
        fields.add(weightData.getLongCol48() != null ? weightData.getLongCol48().toString() : "NULL");
        fields.add(weightData.getLongCol49() != null ? weightData.getLongCol49().toString() : "NULL");
        fields.add(weightData.getLongCol50() != null ? weightData.getLongCol50().toString() : "NULL");
        fields.add(weightData.getLongCol51() != null ? weightData.getLongCol51().toString() : "NULL");
        fields.add(weightData.getLongCol52() != null ? weightData.getLongCol52().toString() : "NULL");
        fields.add(weightData.getLongCol53() != null ? weightData.getLongCol53().toString() : "NULL");
        fields.add(weightData.getLongCol54() != null ? weightData.getLongCol54().toString() : "NULL");
        fields.add(weightData.getLongCol55() != null ? weightData.getLongCol55().toString() : "NULL");
        fields.add(weightData.getLongCol56() != null ? weightData.getLongCol56().toString() : "NULL");
        fields.add(weightData.getLongCol57() != null ? weightData.getLongCol57().toString() : "NULL");
        fields.add(weightData.getLongCol58() != null ? weightData.getLongCol58().toString() : "NULL");
        fields.add(weightData.getLongCol59() != null ? weightData.getLongCol59().toString() : "NULL");
        fields.add(weightData.getLongCol60() != null ? weightData.getLongCol60().toString() : "NULL");
        fields.add(weightData.getLongCol61() != null ? weightData.getLongCol61().toString() : "NULL");
        fields.add(weightData.getLongCol62() != null ? weightData.getLongCol62().toString() : "NULL");
        fields.add(weightData.getLongCol63() != null ? weightData.getLongCol63().toString() : "NULL");
        fields.add(weightData.getLongCol64() != null ? weightData.getLongCol64().toString() : "NULL");
        fields.add(weightData.getLongCol65() != null ? weightData.getLongCol65().toString() : "NULL");
        fields.add(weightData.getLongCol66() != null ? weightData.getLongCol66().toString() : "NULL");
        fields.add(weightData.getLongCol67() != null ? weightData.getLongCol67().toString() : "NULL");
        fields.add(weightData.getLongCol68() != null ? weightData.getLongCol68().toString() : "NULL");
        fields.add(weightData.getLongCol69() != null ? weightData.getLongCol69().toString() : "NULL");
        fields.add(weightData.getLongCol70() != null ? weightData.getLongCol70().toString() : "NULL");
        fields.add(weightData.getLongCol71() != null ? weightData.getLongCol71().toString() : "NULL");
        fields.add(weightData.getLongCol72() != null ? weightData.getLongCol72().toString() : "NULL");
        fields.add(weightData.getLongCol73() != null ? weightData.getLongCol73().toString() : "NULL");
        fields.add(weightData.getLongCol74() != null ? weightData.getLongCol74().toString() : "NULL");
        fields.add(weightData.getLongCol75() != null ? weightData.getLongCol75().toString() : "NULL");
        fields.add(weightData.getLongCol76() != null ? weightData.getLongCol76().toString() : "NULL");
        fields.add(weightData.getLongCol77() != null ? weightData.getLongCol77().toString() : "NULL");
        fields.add(weightData.getLongCol78() != null ? weightData.getLongCol78().toString() : "NULL");
        fields.add(weightData.getLongCol79() != null ? weightData.getLongCol79().toString() : "NULL");
        fields.add(weightData.getLongCol80() != null ? weightData.getLongCol80().toString() : "NULL");
        fields.add(weightData.getLongCol81() != null ? weightData.getLongCol81().toString() : "NULL");
        fields.add(weightData.getLongCol82() != null ? weightData.getLongCol82().toString() : "NULL");
        fields.add(weightData.getLongCol83() != null ? weightData.getLongCol83().toString() : "NULL");
        fields.add(weightData.getLongCol84() != null ? weightData.getLongCol84().toString() : "NULL");
        fields.add(weightData.getLongCol85() != null ? weightData.getLongCol85().toString() : "NULL");
        fields.add(weightData.getLongCol86() != null ? weightData.getLongCol86().toString() : "NULL");
        fields.add(weightData.getLongCol87() != null ? weightData.getLongCol87().toString() : "NULL");
        fields.add(weightData.getLongCol88() != null ? weightData.getLongCol88().toString() : "NULL");
        fields.add(weightData.getLongCol89() != null ? weightData.getLongCol89().toString() : "NULL");
        fields.add(weightData.getLongCol90() != null ? weightData.getLongCol90().toString() : "NULL");
        fields.add(weightData.getLongCol91() != null ? weightData.getLongCol91().toString() : "NULL");
        fields.add(weightData.getLongCol92() != null ? weightData.getLongCol92().toString() : "NULL");
        fields.add(weightData.getLongCol93() != null ? weightData.getLongCol93().toString() : "NULL");
        fields.add(weightData.getLongCol94() != null ? weightData.getLongCol94().toString() : "NULL");
        fields.add(weightData.getLongCol95() != null ? weightData.getLongCol95().toString() : "NULL");
        fields.add(weightData.getLongCol96() != null ? weightData.getLongCol96().toString() : "NULL");
        fields.add(weightData.getLongCol97() != null ? weightData.getLongCol97().toString() : "NULL");
        fields.add(weightData.getLongCol98() != null ? weightData.getLongCol98().toString() : "NULL");
        fields.add(weightData.getLongCol99() != null ? weightData.getLongCol99().toString() : "NULL");
        fields.add(weightData.getLongCol100() != null ? weightData.getLongCol100().toString() : "NULL");
        fields.add(weightData.getStringCol1() != null ? "\'" + weightData.getStringCol1() + "\'"  : "NULL");
        fields.add(weightData.getStringCol2() != null ? "\'" + weightData.getStringCol2() + "\'"  : "NULL");
        fields.add(weightData.getStringCol3() != null ? "\'" + weightData.getStringCol3() + "\'"  : "NULL");
        fields.add(weightData.getStringCol4() != null ? "\'" + weightData.getStringCol4() + "\'"  : "NULL");
        fields.add(weightData.getStringCol5() != null ? "\'" + weightData.getStringCol5() + "\'"  : "NULL");
        fields.add(weightData.getStringCol6() != null ? "\'" + weightData.getStringCol6() + "\'"  : "NULL");
        fields.add(weightData.getStringCol7() != null ? "\'" + weightData.getStringCol7() + "\'"  : "NULL");
        fields.add(weightData.getStringCol8() != null ? "\'" + weightData.getStringCol8() + "\'"  : "NULL");
        fields.add(weightData.getStringCol9() != null ? "\'" + weightData.getStringCol9() + "\'"  : "NULL");
        fields.add(weightData.getStringCol10() != null ? "\'" + weightData.getStringCol10() + "\'"  : "NULL");
        fields.add(weightData.getStringCol11() != null ? "\'" + weightData.getStringCol11() + "\'"  : "NULL");
        fields.add(weightData.getStringCol12() != null ? "\'" + weightData.getStringCol12() + "\'"  : "NULL");
        fields.add(weightData.getStringCol13() != null ? "\'" + weightData.getStringCol13() + "\'"  : "NULL");
        fields.add(weightData.getStringCol14() != null ? "\'" + weightData.getStringCol14() + "\'"  : "NULL");
        fields.add(weightData.getStringCol15() != null ? "\'" + weightData.getStringCol15() + "\'"  : "NULL");
        fields.add(weightData.getStringCol16() != null ? "\'" + weightData.getStringCol16() + "\'"  : "NULL");
        fields.add(weightData.getStringCol17() != null ? "\'" + weightData.getStringCol17() + "\'"  : "NULL");
        fields.add(weightData.getStringCol18() != null ? "\'" + weightData.getStringCol18() + "\'"  : "NULL");
        fields.add(weightData.getStringCol19() != null ? "\'" + weightData.getStringCol19() + "\'"  : "NULL");
        fields.add(weightData.getStringCol20() != null ? "\'" + weightData.getStringCol20() + "\'"  : "NULL");
        fields.add(weightData.getStringCol21() != null ? "\'" + weightData.getStringCol21() + "\'"  : "NULL");
        fields.add(weightData.getStringCol22() != null ? "\'" + weightData.getStringCol22() + "\'"  : "NULL");
        fields.add(weightData.getStringCol23() != null ? "\'" + weightData.getStringCol23() + "\'"  : "NULL");
        fields.add(weightData.getStringCol24() != null ? "\'" + weightData.getStringCol24() + "\'"  : "NULL");
        fields.add(weightData.getStringCol25() != null ? "\'" + weightData.getStringCol25() + "\'"  : "NULL");
        fields.add(weightData.getStringCol26() != null ? "\'" + weightData.getStringCol26() + "\'"  : "NULL");
        fields.add(weightData.getStringCol27() != null ? "\'" + weightData.getStringCol27() + "\'"  : "NULL");
        fields.add(weightData.getStringCol28() != null ? "\'" + weightData.getStringCol28() + "\'"  : "NULL");
        fields.add(weightData.getStringCol29() != null ? "\'" + weightData.getStringCol29() + "\'"  : "NULL");
        fields.add(weightData.getStringCol30() != null ? "\'" + weightData.getStringCol30() + "\'"  : "NULL");
        fields.add(weightData.getStringCol31() != null ? "\'" + weightData.getStringCol31() + "\'"  : "NULL");
        fields.add(weightData.getStringCol32() != null ? "\'" + weightData.getStringCol32() + "\'"  : "NULL");
        fields.add(weightData.getStringCol33() != null ? "\'" + weightData.getStringCol33() + "\'"  : "NULL");
        fields.add(weightData.getStringCol34() != null ? "\'" + weightData.getStringCol34() + "\'"  : "NULL");
        fields.add(weightData.getStringCol35() != null ? "\'" + weightData.getStringCol35() + "\'"  : "NULL");
        fields.add(weightData.getStringCol36() != null ? "\'" + weightData.getStringCol36() + "\'"  : "NULL");
        fields.add(weightData.getStringCol37() != null ? "\'" + weightData.getStringCol37() + "\'"  : "NULL");
        fields.add(weightData.getStringCol38() != null ? "\'" + weightData.getStringCol38() + "\'"  : "NULL");
        fields.add(weightData.getStringCol39() != null ? "\'" + weightData.getStringCol39() + "\'"  : "NULL");
        fields.add(weightData.getStringCol40() != null ? "\'" + weightData.getStringCol40() + "\'"  : "NULL");
        fields.add(weightData.getStringCol41() != null ? "\'" + weightData.getStringCol41() + "\'"  : "NULL");
        fields.add(weightData.getStringCol42() != null ? "\'" + weightData.getStringCol42() + "\'"  : "NULL");
        fields.add(weightData.getStringCol43() != null ? "\'" + weightData.getStringCol43() + "\'"  : "NULL");
        fields.add(weightData.getStringCol44() != null ? "\'" + weightData.getStringCol44() + "\'"  : "NULL");
        fields.add(weightData.getStringCol45() != null ? "\'" + weightData.getStringCol45() + "\'"  : "NULL");
        fields.add(weightData.getStringCol46() != null ? "\'" + weightData.getStringCol46() + "\'"  : "NULL");
        fields.add(weightData.getStringCol47() != null ? "\'" + weightData.getStringCol47() + "\'"  : "NULL");
        fields.add(weightData.getStringCol48() != null ? "\'" + weightData.getStringCol48() + "\'"  : "NULL");
        fields.add(weightData.getStringCol49() != null ? "\'" + weightData.getStringCol49() + "\'"  : "NULL");
        fields.add(weightData.getStringCol50() != null ? "\'" + weightData.getStringCol50() + "\'"  : "NULL");
        fields.add(weightData.getStringCol51() != null ? "\'" + weightData.getStringCol51() + "\'"  : "NULL");
        fields.add(weightData.getStringCol52() != null ? "\'" + weightData.getStringCol52() + "\'"  : "NULL");
        fields.add(weightData.getStringCol53() != null ? "\'" + weightData.getStringCol53() + "\'"  : "NULL");
        fields.add(weightData.getStringCol54() != null ? "\'" + weightData.getStringCol54() + "\'"  : "NULL");
        fields.add(weightData.getStringCol55() != null ? "\'" + weightData.getStringCol55() + "\'"  : "NULL");
        fields.add(weightData.getStringCol56() != null ? "\'" + weightData.getStringCol56() + "\'"  : "NULL");
        fields.add(weightData.getStringCol57() != null ? "\'" + weightData.getStringCol57() + "\'"  : "NULL");
        fields.add(weightData.getStringCol58() != null ? "\'" + weightData.getStringCol58() + "\'"  : "NULL");
        fields.add(weightData.getStringCol59() != null ? "\'" + weightData.getStringCol59() + "\'"  : "NULL");
        fields.add(weightData.getStringCol60() != null ? "\'" + weightData.getStringCol60() + "\'"  : "NULL");
        fields.add(weightData.getStringCol61() != null ? "\'" + weightData.getStringCol61() + "\'"  : "NULL");
        fields.add(weightData.getStringCol62() != null ? "\'" + weightData.getStringCol62() + "\'"  : "NULL");
        fields.add(weightData.getStringCol63() != null ? "\'" + weightData.getStringCol63() + "\'"  : "NULL");
        fields.add(weightData.getStringCol64() != null ? "\'" + weightData.getStringCol64() + "\'"  : "NULL");
        fields.add(weightData.getStringCol65() != null ? "\'" + weightData.getStringCol65() + "\'"  : "NULL");
        fields.add(weightData.getStringCol66() != null ? "\'" + weightData.getStringCol66() + "\'"  : "NULL");
        fields.add(weightData.getStringCol67() != null ? "\'" + weightData.getStringCol67() + "\'"  : "NULL");
        fields.add(weightData.getStringCol68() != null ? "\'" + weightData.getStringCol68() + "\'"  : "NULL");
        fields.add(weightData.getStringCol69() != null ? "\'" + weightData.getStringCol69() + "\'"  : "NULL");
        fields.add(weightData.getStringCol70() != null ? "\'" + weightData.getStringCol70() + "\'"  : "NULL");
        fields.add(weightData.getStringCol71() != null ? "\'" + weightData.getStringCol71() + "\'"  : "NULL");
        fields.add(weightData.getStringCol72() != null ? "\'" + weightData.getStringCol72() + "\'"  : "NULL");
        fields.add(weightData.getStringCol73() != null ? "\'" + weightData.getStringCol73() + "\'"  : "NULL");
        fields.add(weightData.getStringCol74() != null ? "\'" + weightData.getStringCol74() + "\'"  : "NULL");
        fields.add(weightData.getStringCol75() != null ? "\'" + weightData.getStringCol75() + "\'"  : "NULL");
        fields.add(weightData.getStringCol76() != null ? "\'" + weightData.getStringCol76() + "\'"  : "NULL");
        fields.add(weightData.getStringCol77() != null ? "\'" + weightData.getStringCol77() + "\'"  : "NULL");
        fields.add(weightData.getStringCol78() != null ? "\'" + weightData.getStringCol78() + "\'"  : "NULL");
        fields.add(weightData.getStringCol79() != null ? "\'" + weightData.getStringCol79() + "\'"  : "NULL");
        fields.add(weightData.getStringCol80() != null ? "\'" + weightData.getStringCol80() + "\'"  : "NULL");
        fields.add(weightData.getStringCol81() != null ? "\'" + weightData.getStringCol81() + "\'"  : "NULL");
        fields.add(weightData.getStringCol82() != null ? "\'" + weightData.getStringCol82() + "\'"  : "NULL");
        fields.add(weightData.getStringCol83() != null ? "\'" + weightData.getStringCol83() + "\'"  : "NULL");
        fields.add(weightData.getStringCol84() != null ? "\'" + weightData.getStringCol84() + "\'"  : "NULL");
        fields.add(weightData.getStringCol85() != null ? "\'" + weightData.getStringCol85() + "\'"  : "NULL");
        fields.add(weightData.getStringCol86() != null ? "\'" + weightData.getStringCol86() + "\'"  : "NULL");
        fields.add(weightData.getStringCol87() != null ? "\'" + weightData.getStringCol87() + "\'"  : "NULL");
        fields.add(weightData.getStringCol88() != null ? "\'" + weightData.getStringCol88() + "\'"  : "NULL");
        fields.add(weightData.getStringCol89() != null ? "\'" + weightData.getStringCol89() + "\'"  : "NULL");
        fields.add(weightData.getStringCol90() != null ? "\'" + weightData.getStringCol90() + "\'"  : "NULL");
        fields.add(weightData.getStringCol91() != null ? "\'" + weightData.getStringCol91() + "\'"  : "NULL");
        fields.add(weightData.getStringCol92() != null ? "\'" + weightData.getStringCol92() + "\'"  : "NULL");
        fields.add(weightData.getStringCol93() != null ? "\'" + weightData.getStringCol93() + "\'"  : "NULL");
        fields.add(weightData.getStringCol94() != null ? "\'" + weightData.getStringCol94() + "\'"  : "NULL");
        fields.add(weightData.getStringCol95() != null ? "\'" + weightData.getStringCol95() + "\'"  : "NULL");
        fields.add(weightData.getStringCol96() != null ? "\'" + weightData.getStringCol96() + "\'"  : "NULL");
        fields.add(weightData.getStringCol97() != null ? "\'" + weightData.getStringCol97() + "\'"  : "NULL");
        fields.add(weightData.getStringCol98() != null ? "\'" + weightData.getStringCol98() + "\'"  : "NULL");
        fields.add(weightData.getStringCol99() != null ? "\'" + weightData.getStringCol99() + "\'"  : "NULL");
        fields.add(weightData.getStringCol100() != null ? "\'" + weightData.getStringCol100() + "\'"  : "NULL");

        return fields;
    }

    @Override
    public List<String> getStringNamesOfFieldsWithAliasByTable(String table) {
        List<String> fields = this.getStringNamesOfFields();
        return fields.stream().map(field -> table + "." + field + " AS " + table + "_" + field).toList();
    }
}